//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteDireccion
    {
        public int EstudianteID { get; set; }
        public string Direccionfamiliar { get; set; }
        public string DireccionPersonal { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
